services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211
         - PLAYERS=8
         - SERVER_PASSWORD=${SERVER_PASSWORD}
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD=${ADMIN_PASSWORD}
         - COMMUNITY=false
         - SERVER_NAME=${SERVER_NAME}
         - SERVER_DESCRIPTION=${SERVER_DESCRIPTION}
      volumes:
         - ./palworld:/palworld/
